# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_datetime', models.DateTimeField(verbose_name='event time')),
                ('event_location', models.CharField(max_length=200)),
                ('event_presenter', models.CharField(max_length=200)),
            ],
        ),
    ]
