# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_datetime', models.DateTimeField(verbose_name='event time')),
                ('event_end_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='event end time')),
                ('event_location', models.CharField(max_length=200)),
                ('event_presenter', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(choices=[('presentation', 'PRESENTATION'), ('laser show', 'LASER SHOW'), ('dj set', 'DJ SET')], default='presentation', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='event end time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('presentation', 'PRESENTATION'), ('laser show', 'LASER SHOW'), ('dj set', 'DJ SET')], default='presentation', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_presenter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
