# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cal', '0002_auto_20190723_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='event_type',
            field=models.CharField(choices=[('presentation', 'PRESENTATION'), ('laser show', 'LASER SHOW'), ('dj set', 'DJ SET'), ('general', 'GENERAL')], default='presentation', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('presentation', 'PRESENTATION'), ('laser show', 'LASER SHOW'), ('dj set', 'DJ SET'), ('general', 'GENERAL')], default='presentation', max_length=20),
        ),
    ]
